# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alumnos_maestros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='name',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='name',
        ),
        migrations.DeleteModel(
            name='Alumnos',
        ),
        migrations.DeleteModel(
            name='Maestros',
        ),
    ]
