# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alumnos_maestros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='foto',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='foto',
            field=models.ImageField(upload_to='images'),
        ),
    ]
