# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='alumno',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Curso'),
            preserve_default=False,
        ),
    ]
