# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20171027_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('teoria', models.TextField(max_length=100000)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Curso')),
            ],
        ),
    ]
