# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Curso'),
        ),
    ]
