# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20171030_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='curso',
            field=models.ManyToManyField(to='app.Curso'),
        ),
    ]
