# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20171030_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=270)),
                ('resCorrecta', models.CharField(max_length=100)),
                ('resIncorrecta1', models.CharField(max_length=100)),
                ('resIncorrecta2', models.CharField(max_length=100)),
                ('resIncorrecta3', models.CharField(max_length=100)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cuestionario')),
            ],
        ),
    ]
