# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_cuestionario_pregunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='name',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='maestro',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='cuestionario',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='curso',
        ),
        migrations.DeleteModel(
            name='Alumnos',
        ),
        migrations.DeleteModel(
            name='Cuestionario',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Maestros',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
    ]
