# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 05:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_auto_20171105_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('nivel', models.IntegerField(default=0)),
                ('foto', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dificultad', models.CharField(choices=[('1', 'Principiante'), ('2', 'Basico'), ('3', 'Intermedio'), ('4', 'Avanzado')], max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images')),
                ('descripcion', models.TextField(max_length=270)),
            ],
        ),
        migrations.CreateModel(
            name='Maestros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='images')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=270)),
                ('resCorrecta', models.CharField(max_length=100)),
                ('resIncorrecta1', models.CharField(max_length=100)),
                ('resIncorrecta2', models.CharField(max_length=100)),
                ('resIncorrecta3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('teoria', models.TextField(max_length=100000)),
                ('video', models.FileField(blank=True, null=True, upload_to=b'')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tema'),
        ),
        migrations.AddField(
            model_name='curso',
            name='maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Maestros'),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='curso',
            field=models.ManyToManyField(to='app.Curso'),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
