# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20171105_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Rechazado', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PuntuacionMaestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='objetivos',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='requisitos',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='status',
            field=models.CharField(choices=[('Publico', 'Publico'), ('Borrador', 'Borrador'), ('Rechazado', 'Rechazado')], default='Borrador', max_length=30),
        ),
        migrations.AddField(
            model_name='maestro',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='maestro',
            name='titulo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='tema',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='puntuacionmaestro',
            name='maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Maestro'),
        ),
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Categoria'),
            preserve_default=False,
        ),
    ]
