# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20171118_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='status',
            field=models.CharField(choices=[('Aceptado', 'Aceptado')], max_length=25),
        ),
        migrations.AlterField(
            model_name='curso',
            name='status',
            field=models.CharField(choices=[('Publico', 'Publico')], max_length=30),
        ),
    ]
