# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20171119_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='status',
            field=models.CharField(blank=True, choices=[('Aceptado', 'Aceptado')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='status',
            field=models.CharField(blank=True, choices=[('Publico', 'Publico')], max_length=30, null=True),
        ),
    ]
