# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20171127_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=500)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Alumno')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tema')),
            ],
        ),
    ]
