# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='terminado',
            field=models.CharField(blank=True, choices=[('Si', 'Si')], max_length=10, null=True),
        ),
    ]
